[
    {
     "name": "Tostada de Arroz",
     "category": "Sin TACC",
     "type": ["Tostada"],
     "brand": "LULEMUU",
     "price": 90,
     "unit": "120gr",
     "stock": 27,
     "img": "",
     "id": "1"
    },
    {
     "name": "Galletitas de Arroz",
     "category": "Sin TACC",
     "type": ["Galletita"],
     "brand": "CRISPINO",
     "price": 100,
     "unit": "100gr",
     "stock": 37,
     "img": "",
     "id": "2"
    },
    {
     "name": "Harina de Quínoa",
     "category": "Sin TACC",
     "type": ["Harina"],
     "brand": "",
     "price": 330,
     "unit": "250gr",
     "stock": 42,
     "img": "",
     "id": "3"
    },
    {
     "name": "name 4",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 4",
     "price": 75,
     "unit": 27,
     "stock": 5,
     "img": "",
     "id": "4"
    },
    {
     "name": "name 5",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 5",
     "price": 34,
     "unit": 74,
     "stock": 22,
     "img": "",
     "id": "5"
    },
    {
     "name": "name 6",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 6",
     "price": 2,
     "unit": 56,
     "stock": 39,
     "img": "",
     "id": "6"
    },
    {
     "name": "name 7",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 7",
     "price": 72,
     "unit": 75,
     "stock": 51,
     "img": "",
     "id": "7"
    },
    {
     "name": "name 8",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 8",
     "price": 72,
     "unit": 16,
     "stock": 49,
     "img": "",
     "id": "8"
    },
    {
     "name": "name 9",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 9",
     "price": 44,
     "unit": 81,
     "stock": 14,
     "img": "",
     "id": "9"
    },
    {
     "name": "name 10",
     "category": "Sin TACC",
     "type": [],
     "brand": "brand 10",
     "price": 86,
     "unit": 63,
     "stock": 31,
     "img": "",
     "id": "10"
    },
    {
     "name": "name 11",
     "category": "Cereales",
     "type": [],
     "brand": "brand 11",
     "price": 99,
     "unit": 16,
     "stock": 2,
     "img": "",
     "id": "11"
    },
    {
     "name": "name 12",
     "category": "Cereales",
     "type": [],
     "brand": "brand 12",
     "price": 71,
     "unit": 97,
     "stock": 44,
     "img": "",
     "id": "12"
    },
    {
     "name": "name 13",
     "category": "Cereales",
     "type": [],
     "brand": "brand 13",
     "price": 12,
     "unit": 57,
     "stock": 44,
     "img": "",
     "id": "13"
    },
    {
     "name": "name 14",
     "category": "Cereales",
     "type": [],
     "brand": "brand 14",
     "price": 89,
     "unit": 54,
     "stock": 57,
     "img": "",
     "id": "14"
    },
    {
     "name": "name 15",
     "category": "Cereales",
     "type": [],
     "brand": "brand 15",
     "price": 54,
     "unit": 50,
     "stock": 30,
     "img": "",
     "id": "15"
    },
    {
     "name": "name 16",
     "category": "Cereales",
     "type": [],
     "brand": "brand 16",
     "price": 47,
     "unit": 21,
     "stock": 56,
     "img": "",
     "id": "16"
    },
    {
     "name": "name 17",
     "category": "Cereales",
     "type": [],
     "brand": "brand 17",
     "price": 8,
     "unit": 88,
     "stock": 54,
     "img": "",
     "id": "17"
    },
    {
     "name": "name 18",
     "category": "Cereales",
     "type": [],
     "brand": "brand 18",
     "price": 54,
     "unit": 1,
     "stock": 4,
     "img": "",
     "id": "18"
    },
    {
     "name": "name 19",
     "category": "Cereales",
     "type": [],
     "brand": "brand 19",
     "price": 89,
     "unit": 66,
     "stock": 15,
     "img": "",
     "id": "19"
    },
    {
     "name": "name 20",
     "category": "Cereales",
     "type": [],
     "brand": "brand 20",
     "price": 77,
     "unit": 65,
     "stock": 4,
     "img": "",
     "id": "20"
    },
    {
     "name": "name 21",
     "category": "Congelados",
     "type": [],
     "brand": "brand 21",
     "price": 51,
     "unit": 93,
     "stock": 21,
     "img": "",
     "id": "21"
    },
    {
     "name": "name 22",
     "category": "Congelados",
     "type": [],
     "brand": "brand 22",
     "price": 99,
     "unit": 53,
     "stock": 3,
     "img": "",
     "id": "22"
    },
    {
     "name": "name 23",
     "category": "Congelados",
     "type": [],
     "brand": "brand 23",
     "price": 85,
     "unit": 79,
     "stock": 10,
     "img": "",
     "id": "23"
    },
    {
     "name": "name 24",
     "category": "Congelados",
     "type": [],
     "brand": "brand 24",
     "price": 82,
     "unit": 68,
     "stock": 67,
     "img": "",
     "id": "24"
    },
    {
     "name": "name 25",
     "category": "Congelados",
     "type": [],
     "brand": "brand 25",
     "price": 57,
     "unit": 59,
     "stock": 19,
     "img": "",
     "id": "25"
    },
    {
     "name": "name 26",
     "category": "Congelados",
     "type": [],
     "brand": "brand 26",
     "price": 36,
     "unit": 50,
     "stock": 96,
     "img": "",
     "id": "26"
    },
    {
     "name": "name 27",
     "category": "Congelados",
     "type": [],
     "brand": "brand 27",
     "price": 75,
     "unit": 92,
     "stock": 46,
     "img": "",
     "id": "27"
    },
    {
     "name": "name 28",
     "category": "Congelados",
     "type": [],
     "brand": "brand 28",
     "price": 79,
     "unit": 81,
     "stock": 40,
     "img": "",
     "id": "28"
    },
    {
     "name": "name 29",
     "category": "Congelados",
     "type": [],
     "brand": "brand 29",
     "price": 83,
     "unit": 30,
     "stock": 83,
     "img": "",
     "id": "29"
    },
    {
     "name": "name 30",
     "category": "Congelados",
     "type": [],
     "brand": "brand 30",
     "price": 27,
     "unit": 28,
     "stock": 4,
     "img": "",
     "id": "30"
    }
   ]